### ISSUE TITLE
Links go to the wrong page

### ISSUE THREAD

**Issue by dakshisdakshs** [dakshisdakshs/website_issues#3]
<img width="1338" alt="Screenshot 2024-03-12 at 11 21 35 AM" src="https://github.com/dakshisdakshs/website_issues/assets/158471641/dde625d8-e780-4753-8158-32063381f77d">

**Comment by abhideepkumar** [comment]
we need more info regarding this in order to solve it.
Can you describe which link you want to open and what is opening.
